// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 04 Jul 2024 09:53:47 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <kuzu.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

