// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 03 Jul 2024 16:02:13 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <kuzu.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

