// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 04 Jul 2024 09:53:47 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package kuzu

/*
#cgo LDFLAGS: -lkuzu
#include <kuzu.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

const (
	// KUZU_HELPER_DLL_IMPORT as defined in include/kuzu.h:13
	KUZU_HELPER_DLL_IMPORT = 0x626140
	// KUZU_HELPER_DLL_EXPORT as defined in include/kuzu.h:14
	KUZU_HELPER_DLL_EXPORT = 0x626140
	// KUZU_HELPER_DLL_LOCAL as defined in include/kuzu.h:15
	KUZU_HELPER_DLL_LOCAL = 0x626140
	// KUZU_HELPER_DEPRECATED as defined in include/kuzu.h:16
	KUZU_HELPER_DEPRECATED = 0x626140
	// KUZU_API as defined in include/kuzu.h:29
	KUZU_API = KUZU_HELPER_DLL_IMPORT
	// KUZU_DEPRECATED as defined in include/kuzu.h:36
	KUZU_DEPRECATED = KUZU_HELPER_DEPRECATED
)

// DataTypeId as declared in include/kuzu.h:308
type DataTypeId int32

// DataTypeId enumeration from include/kuzu.h:308
const (
	KUZU_ANY           DataTypeId = C.KUZU_ANY
	KUZU_NODE          DataTypeId = C.KUZU_NODE
	KUZU_REL           DataTypeId = C.KUZU_REL
	KUZU_RECURSIVE_REL DataTypeId = C.KUZU_RECURSIVE_REL
	KUZU_SERIAL        DataTypeId = C.KUZU_SERIAL
	KUZU_BOOL          DataTypeId = C.KUZU_BOOL
	KUZU_INT64         DataTypeId = C.KUZU_INT64
	KUZU_INT32         DataTypeId = C.KUZU_INT32
	KUZU_INT16         DataTypeId = C.KUZU_INT16
	KUZU_INT8          DataTypeId = C.KUZU_INT8
	KUZU_UINT64        DataTypeId = C.KUZU_UINT64
	KUZU_UINT32        DataTypeId = C.KUZU_UINT32
	KUZU_UINT16        DataTypeId = C.KUZU_UINT16
	KUZU_UINT8         DataTypeId = C.KUZU_UINT8
	KUZU_INT128        DataTypeId = C.KUZU_INT128
	KUZU_DOUBLE        DataTypeId = C.KUZU_DOUBLE
	KUZU_FLOAT         DataTypeId = C.KUZU_FLOAT
	KUZU_DATE          DataTypeId = C.KUZU_DATE
	KUZU_TIMESTAMP     DataTypeId = C.KUZU_TIMESTAMP
	KUZU_TIMESTAMP_SEC DataTypeId = C.KUZU_TIMESTAMP_SEC
	KUZU_TIMESTAMP_MS  DataTypeId = C.KUZU_TIMESTAMP_MS
	KUZU_TIMESTAMP_NS  DataTypeId = C.KUZU_TIMESTAMP_NS
	KUZU_TIMESTAMP_TZ  DataTypeId = C.KUZU_TIMESTAMP_TZ
	KUZU_INTERVAL      DataTypeId = C.KUZU_INTERVAL
	KUZU_INTERNAL_ID   DataTypeId = C.KUZU_INTERNAL_ID
	KUZU_STRING        DataTypeId = C.KUZU_STRING
	KUZU_BLOB          DataTypeId = C.KUZU_BLOB
	KUZU_LIST          DataTypeId = C.KUZU_LIST
	KUZU_ARRAY         DataTypeId = C.KUZU_ARRAY
	KUZU_STRUCT        DataTypeId = C.KUZU_STRUCT
	KUZU_MAP           DataTypeId = C.KUZU_MAP
	KUZU_UNION         DataTypeId = C.KUZU_UNION
	KUZU_RDF_VARIANT   DataTypeId = C.KUZU_RDF_VARIANT
	KUZU_POINTER       DataTypeId = C.KUZU_POINTER
	KUZU_UUID          DataTypeId = C.KUZU_UUID
)
