// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Thu, 04 Jul 2024 09:53:47 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package kuzu provides Go bindings for the Kùzu embeddable graph database.
*/
package kuzu
