// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Wed, 03 Jul 2024 16:02:13 PDT.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package kuzu

/*
#cgo LDFLAGS: -lkuzu
#include <kuzu.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import "unsafe"

// SystemConfig as declared in include/kuzu.h:125
type SystemConfig struct {
	BufferPoolSize    uint64
	MaxNumThreads     uint64
	EnableCompression bool
	ReadOnly          bool
	MaxDbSize         uint64
	ref49fc98ca       *C.kuzu_system_config
	allocs49fc98ca    interface{}
}

// Database as declared in include/kuzu.h:132
type Database struct {
	Database       unsafe.Pointer
	ref57d0c6d0    *C.kuzu_database
	allocs57d0c6d0 interface{}
}

// Connection as declared in include/kuzu.h:141
type Connection struct {
	Connection     unsafe.Pointer
	ref38ace366    *C.kuzu_connection
	allocs38ace366 interface{}
}

// PreparedStatement as declared in include/kuzu.h:150
type PreparedStatement struct {
	PreparedStatement unsafe.Pointer
	BoundValues       unsafe.Pointer
	ref7af57e99       *C.kuzu_prepared_statement
	allocs7af57e99    interface{}
}

// QueryResult as declared in include/kuzu.h:158
type QueryResult struct {
	QueryResult    unsafe.Pointer
	IsOwnedByCpp   bool
	ref96f12068    *C.kuzu_query_result
	allocs96f12068 interface{}
}

// FlatTuple as declared in include/kuzu.h:165
type FlatTuple struct {
	FlatTuple      unsafe.Pointer
	ref9d13df43    *C.kuzu_flat_tuple
	allocs9d13df43 interface{}
}

// LogicalType as declared in include/kuzu.h:172
type LogicalType struct {
	DataType       unsafe.Pointer
	refbd1fd0f6    *C.kuzu_logical_type
	allocsbd1fd0f6 interface{}
}

// Value as declared in include/kuzu.h:180
type Value struct {
	Value          unsafe.Pointer
	IsOwnedByCpp   bool
	refd5f476b4    *C.kuzu_value
	allocsd5f476b4 interface{}
}

// InternalIdT as declared in include/kuzu.h:188
type InternalIdT struct {
	TableId        uint64
	Offset         uint64
	ref2387636b    *C.kuzu_internal_id_t
	allocs2387636b interface{}
}

// DateT as declared in include/kuzu.h:196
type DateT struct {
	Days           int32
	refab8f78a2    *C.kuzu_date_t
	allocsab8f78a2 interface{}
}

// TimestampNsT as declared in include/kuzu.h:205
type TimestampNsT struct {
	Value          int64
	refe2f90830    *C.kuzu_timestamp_ns_t
	allocse2f90830 interface{}
}

// TimestampMsT as declared in include/kuzu.h:214
type TimestampMsT struct {
	Value          int64
	reff04ca7de    *C.kuzu_timestamp_ms_t
	allocsf04ca7de interface{}
}

// TimestampSecT as declared in include/kuzu.h:223
type TimestampSecT struct {
	Value          int64
	ref155229e1    *C.kuzu_timestamp_sec_t
	allocs155229e1 interface{}
}

// TimestampTzT as declared in include/kuzu.h:232
type TimestampTzT struct {
	Value          int64
	refd28c8444    *C.kuzu_timestamp_tz_t
	allocsd28c8444 interface{}
}

// TimestampT as declared in include/kuzu.h:241
type TimestampT struct {
	Value          int64
	ref232f4437    *C.kuzu_timestamp_t
	allocs232f4437 interface{}
}

// IntervalT as declared in include/kuzu.h:250
type IntervalT struct {
	Months         int32
	Days           int32
	Micros         int64
	ref22729eeb    *C.kuzu_interval_t
	allocs22729eeb interface{}
}

// QuerySummary as declared in include/kuzu.h:258
type QuerySummary struct {
	QuerySummary  unsafe.Pointer
	ref97a5536    *C.kuzu_query_summary
	allocs97a5536 interface{}
}

// Int128T as declared in include/kuzu.h:263
type Int128T struct {
	Low            uint64
	High           int64
	reff96f3de2    *C.kuzu_int128_t
	allocsf96f3de2 interface{}
}
